# Generated by Django 5.0.2 on 2024-03-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_rename_to_location_bookcar_drop_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcar',
            old_name='pickup_location',
            new_name='from_location',
        ),
        migrations.RenameField(
            model_name='bookcar',
            old_name='drop_location',
            new_name='to_location',
        ),
    ]
